### ISSUE TITLE
Back End Product page not loading after install

### ISSUE THREAD

**Issue by cooltidecol** [adampmoss/CreareSEO#93]
I may have found an issue.
I installed the CreareSEO Magento Extension - ef9dfcf4728db6494512f2eaea639bf533d0f3ef - I am using Magento 1.9.2.2 Community Edition
When I select "Make "alt" tags mandatory on product gallery images?" under SEO settings, the product page does not load correctly (See Link below) . When it's set to "No" the product page loads correctly
[http://www.farranoir.com/img/github.png](url)

This only affects the back end, not the front end website

Any ideas?

Thanks in advance

Kind regards

Colin (colin@cooltide.ocm)

**Comment by adampmoss** [comment]
Hi Colin, can you try the latest version of the extension as I believe this has been fixed: https://github.com/adampmoss/CreareSEO/releases

**Comment by joost-heijden** [comment]
I've got the same problem. When i upgrade to 1.5.1, my version stays in CreareSEO version 1.5, under system. Did i do something wrong?
![schermafbeelding 2017-06-14 om 12 29 31](https://user-images.githubusercontent.com/29427775/27127979-2b3b837a-50fd-11e7-8352-2211b6467b59.png)

**Comment by adampmoss** [comment]
Hi all, this is because mistakenly the XML wasn't updated in the last release, it still says:

`<version>1.5</version>`

You should have the latest version though anyway, I will correct this XML in the next release.

**Comment by joost-heijden** [comment]
Thanks for ya feedback! But it still doesn't work for me. Is there another thing i can do, to fix this problem?

**Comment by joost-heijden** [comment]
I read something to change: gallery.phtml to gallery.phtml.bak. Then i see my backend again. But not my pictures.. Hope you will have a solution.

**Comment by timothyCoxon** [comment]
+1 for this issue.
Fresh install on 1.9.2.4 test site (very few other extensions and no real data)
Running the github version about 2 hrs ago. (last commit bdaf4b6)

When I have enforced alt tags set active the backend products pages break. Get a unstyled view of the image upload section and nothing else.
Works fine without enforced alt tags.

**Comment by sprankhub** [comment]
You should be fine if you use the latest Magento 1.9.3.6 release.

If you want to stick to Magento 1.9.2.x, what I would not recommend at all, and definitely want to use the "force alt tags" feature, you can:

1. Copy contents from `app/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml` to `app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml`
2. Replace:

        <td class="cell-label"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>

    with:

        <td class="cell-label"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text required-entry" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>

It should work then.
